"""microquantum: A lightweight Python quantum computing SDK."""

__version__ = "0.3.0"

from .adapters import DomainAdapter, QuantumProblem, QuantumResult, ResultCache
from .algorithms import (
    HHL,
    QAOA,
    QFT,
    VQD,
    VQE,
    AdaptResult,
    AdaptVQE,
    Algorithm,
    AmplitudeEstimation,
    AmplitudeEstimationResult,
    BernsteinVazirani,
    BVResult,
    ContinuousQuantumWalk,
    DeutschJozsa,
    DiscreteQuantumWalk,
    DJResult,
    GroverResult,
    GroverSearch,
    HamiltonianSimulation,
    HHLResult,
    PhaseEstimation,
    PhaseEstimationResult,
    QuantumWalkResult,
    ShorResult,
    ShorsAlgorithm,
    TrotterResult,
    VQDResult,
    VQEResult,
    fourth_order_simulation,
    inverse_qft_circuit,
    qdrift_simulation,
    qft_circuit,
)
from .analytics import AnalysisResult, BaseAnalytics, Result
from .backends import (
    Backend,
    BackendResult,
    DensityMatrixBackend,
    Executor,
    ExecutorResult,
    Job,
    JobStatus,
    MatrixProductState,
    MPSBackend,
    NoiseChannel,
    NoiseModel,
    StatevectorBackend,
    TreeTensorNetwork,
    TreeTensorNetworkBackend,
    available_backends,
    get_array_backend,
    gpu_available,
    is_gpu,
    set_array_backend,
)
from .benchmarks import (
    BenchmarkResult,
    CLOPSBenchmark,
    CrossEntropyBenchmarking,
    CycleBenchmarking,
    CycleBenchmarkingResult,
    GateSetTomography,
    GSTResult,
    LayerFidelity,
    LayerFidelityResult,
    PauliTwirling,
    QuantumVolumeBenchmark,
    RandomizedBenchmarking,
    RandomizedBenchmarkingResult,
    TwirlingResult,
    XEBResult,
)
from .chemistry import (
    H2Hamiltonian,
    HardwareEfficientAnsatz,
    LiHHamiltonian,
    MolecularHamiltonian,
    UCCSDAnsatz,
)
from .core import (
    CouplingMap,
    Device,
    DeviceType,
    MeasurementResult,
    Operator,
    Parameter,
    ParameterExpression,
    Pass,
    PassManager,
    PauliString,
    PauliSum,
    QuantumCircuit,
    ResourceEstimate,
    ResourceEstimator,
    StateVector,
    Target,
    TargetGateSet,
    apply_gate,
    cancel_inverse_pairs,
    circuit_stats,
    expand_operator,
    expectation_value,
    fuse_single_qubit_gates,
    gradient,
    measure_and_collapse,
    measure_qubits,
    parameter_shift_gradient,
    remove_identity_gates,
    sample_state,
    simplify_circuit,
    tensor,
    transpile,
)
from .core.density_matrix import DensityMatrix
from .core.dynamic import ClassicalRegister, DynamicCircuit, DynamicCircuitResult
from .core.registers import ClassicalRegister as ClassicalRegisterBase
from .core.registers import QuantumRegister
from .mitigation import (
    ExtrapolationResult,
    MeasurementErrorMitigation,
    MitigationMatrix,
    ProbabilisticErrorCancellation,
    ZeroNoiseExtrapolation,
)
from .optimization import IsingConverter, QUBOBuilder, QUBOProblem
from .optimizers import (
    COBYLA,
    QNSPSA,
    SPSA,
    Adam,
    GradientDescent,
    NelderMead,
    Optimizer,
    OptimizerResult,
)
from .providers import (
    CircuitSerializer,
    HardwareBackend,
    HardwareJob,
    HardwareProvider,
    HardwareStatus,
    IBMQuantumCredentials,
    IBMQuantumProvider,
    IonQCredentials,
    IonQProvider,
    ProviderCredentials,
    UnsupportedGateError,
)
from .qec import BitFlipCode, PhaseFlipCode, RepetitionCode, ShorCode
from .qml import (
    AmplitudeEncoding,
    AngleEncoding,
    ClassifierResult,
    IQPEncoding,
    QuantumKernel,
    VariationalClassifier,
    ZFeatureMap,
)

__all__ = [
    # Core
    "CouplingMap",
    "QuantumCircuit",
    "StateVector",
    "DensityMatrix",
    "Operator",
    "Parameter",
    "ParameterExpression",
    "PauliString",
    "PauliSum",
    "QuantumRegister",
    "ClassicalRegisterBase",
    "apply_gate",
    "tensor",
    "expand_operator",
    "MeasurementResult",
    "sample_state",
    "measure_qubits",
    "measure_and_collapse",
    "expectation_value",
    "parameter_shift_gradient",
    "gradient",
    # Circuit optimization
    "fuse_single_qubit_gates",
    "remove_identity_gates",
    "cancel_inverse_pairs",
    "simplify_circuit",
    "transpile",
    "circuit_stats",
    # Transpiler
    "Pass",
    "PassManager",
    "TargetGateSet",
    # Device & target contracts
    "Device",
    "DeviceType",
    "Target",
    # Dynamic circuits
    "DynamicCircuit",
    "DynamicCircuitResult",
    "ClassicalRegister",
    # Resources
    "ResourceEstimator",
    "ResourceEstimate",
    # Backends
    "Backend",
    "BackendResult",
    "Job",
    "JobStatus",
    "StatevectorBackend",
    "DensityMatrixBackend",
    "MatrixProductState",
    "MPSBackend",
    "TreeTensorNetwork",
    "TreeTensorNetworkBackend",
    "NoiseModel",
    "NoiseChannel",
    "Executor",
    "ExecutorResult",
    "set_array_backend",
    "get_array_backend",
    "available_backends",
    "gpu_available",
    "is_gpu",
    # Optimizers
    "Optimizer",
    "OptimizerResult",
    "GradientDescent",
    "Adam",
    "COBYLA",
    "NelderMead",
    "SPSA",
    "QNSPSA",
    # Algorithms
    "Algorithm",
    "VQE",
    "VQEResult",
    "QAOA",
    "GroverSearch",
    "GroverResult",
    "AmplitudeEstimation",
    "AmplitudeEstimationResult",
    "QFT",
    "qft_circuit",
    "inverse_qft_circuit",
    "PhaseEstimation",
    "PhaseEstimationResult",
    "HamiltonianSimulation",
    "TrotterResult",
    "HHL",
    "HHLResult",
    "VQD",
    "VQDResult",
    "AdaptVQE",
    "AdaptResult",
    "DiscreteQuantumWalk",
    "ContinuousQuantumWalk",
    "QuantumWalkResult",
    "ShorsAlgorithm",
    "ShorResult",
    "BernsteinVazirani",
    "BVResult",
    "DeutschJozsa",
    "DJResult",
    "fourth_order_simulation",
    "qdrift_simulation",
    # QEC
    "RepetitionCode",
    "BitFlipCode",
    "PhaseFlipCode",
    "ShorCode",
    # Adapters
    "DomainAdapter",
    "QuantumProblem",
    "QuantumResult",
    "ResultCache",
    # QML
    "AngleEncoding",
    "AmplitudeEncoding",
    "IQPEncoding",
    "ZFeatureMap",
    "QuantumKernel",
    "VariationalClassifier",
    "ClassifierResult",
    # Mitigation
    "ZeroNoiseExtrapolation",
    "ExtrapolationResult",
    "ProbabilisticErrorCancellation",
    "MeasurementErrorMitigation",
    "MitigationMatrix",
    # Chemistry
    "MolecularHamiltonian",
    "H2Hamiltonian",
    "LiHHamiltonian",
    "HardwareEfficientAnsatz",
    "UCCSDAnsatz",
    # Benchmarks
    "QuantumVolumeBenchmark",
    "BenchmarkResult",
    "CLOPSBenchmark",
    "RandomizedBenchmarking",
    "RandomizedBenchmarkingResult",
    "CrossEntropyBenchmarking",
    "XEBResult",
    "GateSetTomography",
    "GSTResult",
    "CycleBenchmarking",
    "CycleBenchmarkingResult",
    "LayerFidelity",
    "LayerFidelityResult",
    "PauliTwirling",
    "TwirlingResult",
    # Analytics
    "AnalysisResult",
    "BaseAnalytics",
    "Result",
    # Optimization
    "QUBOBuilder",
    "QUBOProblem",
    "IsingConverter",
    # Providers
    "HardwareProvider",
    "HardwareJob",
    "HardwareStatus",
    "ProviderCredentials",
    "HardwareBackend",
    "IBMQuantumCredentials",
    "IBMQuantumProvider",
    "IonQCredentials",
    "IonQProvider",
    "CircuitSerializer",
    "UnsupportedGateError",
]
