"""microquantum: A lightweight Python quantum computing SDK.

Package ecosystem
-----------------
The public surface follows a stable, layered package layout (see
``docs/developer-guide/package-ecosystem.rst`` for the full map):

- ``microquantum.core`` — engine: circuits (``core.circuit``), operators/gate
  library (``core.operators``), states (``core.state``), measurement
  (``core.measurement``), transpiler passes, parameters, registers.
- ``microquantum.ir`` — the compiler layer: the semantic intermediate
  representation, its passes and ``Compiler``.
- ``microquantum.runtime`` — execution plans, the execution runtime and its
  strategies.
- ``microquantum.backends`` — the backend contract, capabilities/registry and
  local simulators.
- ``microquantum.stdlib`` — the system standard library: ``stdlib.bits``,
  ``stdlib.numbers`` and ``stdlib.states`` factories.

``__init__`` is the friendly gateway: names are re-exported from their single
canonical home so ``from microquantum import X`` always resolves to the same
object as the subpackage import.  Private implementation helpers stay private
(module-level ``_`` prefix) and are not part of the public surface; the entire
private module boundary is ``microquantum._json`` (JSON helpers) and
``microquantum._cli`` (developer CLI).
"""

__version__ = "1.0.0"

from .adapters import DomainAdapter, QuantumProblem, QuantumResult, ResultCache
from .algorithms import (
    HHL,
    QAOA,
    QFT,
    VQD,
    VQE,
    AdaptResult,
    AdaptVQE,
    Algorithm,
    AlgorithmResult,
    AmplitudeEstimation,
    AmplitudeEstimationResult,
    BernsteinVazirani,
    BVResult,
    ContinuousQuantumWalk,
    DeutschJozsa,
    DiscreteQuantumWalk,
    DJResult,
    GroverResult,
    GroverSearch,
    HamiltonianSimulation,
    HHLResult,
    PhaseEstimation,
    PhaseEstimationResult,
    QuantumWalkResult,
    ShorResult,
    ShorsAlgorithm,
    TrotterResult,
    VQDResult,
    VQEResult,
    fourth_order_simulation,
    inverse_qft_circuit,
    qdrift_simulation,
    qft_circuit,
)
from .analysis import (
    ExpectationAnalysis,
    ResultAggregator,
    SamplingAnalysis,
    StateAnalysis,
    confidence_interval,
    count,
    maximum,
    mean,
    minimum,
    standard_deviation,
    standard_error,
    variance,
)
from .analytics import AnalysisResult, BaseAnalytics, Result
from .backends import (
    Backend,
    BackendAdapter,
    BackendCapabilities,
    BackendRegistry,
    BackendResult,
    DensityMatrixBackend,
    Executor,
    ExecutorResult,
    Job,
    JobStatus,
    LocalProvider,
    LocalSimulatorBackend,
    MatrixProductState,
    MockBackend,
    MPSBackend,
    NoiseChannel,
    NoiseModel,
    Provider,
    StatevectorBackend,
    TargetClass,
    TreeTensorNetwork,
    TreeTensorNetworkBackend,
    available_backends,
    get_array_backend,
    gpu_available,
    is_gpu,
    set_array_backend,
)
from .benchmarks import (
    BenchmarkResult,
    CLOPSBenchmark,
    CrossEntropyBenchmarking,
    CycleBenchmarking,
    CycleBenchmarkingResult,
    GateSetTomography,
    GSTResult,
    LayerFidelity,
    LayerFidelityResult,
    PauliTwirling,
    QuantumVolumeBenchmark,
    RandomizedBenchmarking,
    RandomizedBenchmarkingResult,
    TwirlingResult,
    XEBResult,
)
from .chemistry import (
    H2Hamiltonian,
    HardwareEfficientAnsatz,
    LiHHamiltonian,
    MolecularHamiltonian,
    UCCSDAnsatz,
)
from .core import (
    POVM,
    AnalysisPass,
    CircuitResources,
    Clbit,
    CompositeGate,
    ControlledGate,
    CouplingMap,
    Device,
    DeviceType,
    ExecutionRequest,
    GradientEngine,
    GradientResult,
    HermitianOperator,
    KrausChannel,
    LinearOperator,
    MatrixObservable,
    MeasurementResult,
    NativeGateSet,
    Observable,
    Operator,
    Parameter,
    ParameterBinding,
    ParameterExpression,
    ParameterizedGate,
    ParameterVector,
    Pass,
    PassContext,
    PassManager,
    PauliObservable,
    PauliString,
    PauliSum,
    ProjectiveMeasurement,
    Projector,
    QuantumArchitecture,
    QuantumChannel,
    QuantumCircuit,
    Qubit,
    QubitTopology,
    Register,
    ResourceEstimate,
    ResourceEstimator,
    State,
    StateVector,
    SumObservable,
    Target,
    TargetGateSet,
    TransformationPass,
    UnitaryGate,
    UnitaryOperator,
    anticommutes,
    apply_gate,
    cancel_inverse_pairs,
    circuit_stats,
    commutes,
    deserialize_circuit,
    estimate_resources,
    expand_operator,
    expectation_value,
    fidelity,
    fuse_single_qubit_gates,
    gradient,
    iter_instructions,
    measure_and_collapse,
    measure_qubits,
    parameter_shift_gradient,
    remove_identity_gates,
    sample_state,
    serialize_circuit,
    simplify_circuit,
    tensor,
    trace_distance,
    transpile,
    validate_circuit,
    von_neumann_entropy,
)
from .core.density_matrix import DensityMatrix
from .core.dynamic import ClassicalRegister, DynamicCircuit, DynamicCircuitResult
from .core.registers import ClassicalRegister as ClassicalRegisterBase
from .core.registers import QuantumRegister
from .experiments import (
    ExecutionFailure,
    ExecutionRecord,
    ExecutionStatus,
    Experiment,
    ExperimentResult,
    ParameterSweep,
    execution_fingerprint,
    reproducibility_metadata,
)
from .ir import (
    Barrier,
    BindParameters,
    CancelAdjacentInverse,
    CombineRotations,
    CompilationResult,
    Compiler,
    Condition,
    ConditionalBlock,
    Gate,
    GateDecomposition,
    IRCircuit,
    IRModule,
    IRNode,
    IRParam,
    IRPass,
    IRPassManager,
    Measurement,
    RemoveIdentityGates,
    Reset,
    assert_valid,
    from_ir,
    optimize,
    to_ir,
    to_ir_dynamic,
    validate,
)
from .mitigation import (
    ExtrapolationResult,
    MeasurementErrorMitigation,
    MitigationMatrix,
    ProbabilisticErrorCancellation,
    ZeroNoiseExtrapolation,
)
from .optimization import IsingConverter, QUBOBuilder, QUBOProblem
from .optimizers import (
    BFGS,
    COBYLA,
    QNSPSA,
    SPSA,
    Adam,
    GradientDescent,
    NelderMead,
    Optimizer,
    OptimizerResult,
)
from .problems import (
    EigenvalueProblem,
    HamiltonianProblem,
    OptimizationProblem,
    Problem,
    SamplingProblem,
    SearchProblem,
)
from .providers import (
    CircuitSerializer,
    HardwareBackend,
    HardwareJob,
    HardwareProvider,
    HardwareStatus,
    IBMQuantumCredentials,
    IBMQuantumProvider,
    IonQCredentials,
    IonQProvider,
    ProviderCredentials,
    UnsupportedGateError,
)
from .qec import BitFlipCode, PhaseFlipCode, RepetitionCode, ShorCode
from .qml import (
    AmplitudeEncoding,
    AngleEncoding,
    ClassifierResult,
    IQPEncoding,
    QuantumKernel,
    VariationalClassifier,
    ZFeatureMap,
)
from .runtime import (
    STRATEGY_HANDLERS,
    ExecutionPlan,
    ExecutionRuntime,
    ExecutionStrategy,
    ExecutionTrace,
    RuntimeConfig,
    TraceEvent,
    default_runtime,
    execute,
    execute_batch,
    execute_records,
    register_custom_strategy,
    run_experiment,
    run_hybrid,
    run_parameter_sweep,
    runtime_info,
    submit,
    submit_batch,
)
from .stdlib import (
    basis_state,
    bell_state,
    bits_to_int,
    bitstring_to_int,
    ghz_state,
    hamming_distance,
    hamming_weight,
    int_to_bits,
    int_to_bitstring,
    is_angle_close,
    is_identity_angle,
    mod_2pi,
    uniform_superposition,
    w_state,
    wrap_angle,
)

__all__ = [
    # Standard Library (Phase 117)
    "stdlib",
    "int_to_bits",
    "bits_to_int",
    "int_to_bitstring",
    "bitstring_to_int",
    "hamming_weight",
    "hamming_distance",
    "mod_2pi",
    "wrap_angle",
    "is_angle_close",
    "is_identity_angle",
    "basis_state",
    "uniform_superposition",
    "bell_state",
    "ghz_state",
    "w_state",
    # Core
    "CouplingMap",
    "QuantumCircuit",
    "StateVector",
    "DensityMatrix",
    "Operator",
    "Parameter",
    "ParameterExpression",
    "PauliString",
    "PauliSum",
    "QuantumRegister",
    "ClassicalRegisterBase",
    "apply_gate",
    "tensor",
    "expand_operator",
    "MeasurementResult",
    "sample_state",
    "measure_qubits",
    "measure_and_collapse",
    "expectation_value",
    "parameter_shift_gradient",
    "gradient",
    # Expanded Core foundations
    "AnalysisPass",
    "CircuitResources",
    "Clbit",
    "CompositeGate",
    "ControlledGate",
    "ExecutionRequest",
    "GradientEngine",
    "GradientResult",
    "HermitianOperator",
    "KrausChannel",
    "LinearOperator",
    "MatrixObservable",
    "NativeGateSet",
    "Observable",
    "ParameterBinding",
    "ParameterVector",
    "ParameterizedGate",
    "PassContext",
    "PauliObservable",
    "POVM",
    "ProjectiveMeasurement",
    "Projector",
    "QuantumArchitecture",
    "QuantumChannel",
    "Qubit",
    "QubitTopology",
    "Register",
    "State",
    "SumObservable",
    "TransformationPass",
    "UnitaryGate",
    "UnitaryOperator",
    "anticommutes",
    "commutes",
    "deserialize_circuit",
    "estimate_resources",
    "fidelity",
    "iter_instructions",
    "serialize_circuit",
    "trace_distance",
    "validate_circuit",
    "von_neumann_entropy",
    # Circuit optimization
    "fuse_single_qubit_gates",
    "remove_identity_gates",
    "cancel_inverse_pairs",
    "simplify_circuit",
    "transpile",
    "circuit_stats",
    # Transpiler
    "Pass",
    "PassManager",
    "TargetGateSet",
    # Device & target contracts
    "Device",
    "DeviceType",
    "Target",
    # Dynamic circuits
    "DynamicCircuit",
    "DynamicCircuitResult",
    "ClassicalRegister",
    # IR & compilation
    "IRCircuit",
    "IRModule",
    "IRNode",
    "IRParam",
    "Gate",
    "Measurement",
    "Reset",
    "Barrier",
    "Condition",
    "ConditionalBlock",
    "to_ir",
    "to_ir_dynamic",
    "from_ir",
    "validate",
    "assert_valid",
    "IRPass",
    "IRPassManager",
    "RemoveIdentityGates",
    "CancelAdjacentInverse",
    "CombineRotations",
    "BindParameters",
    "GateDecomposition",
    "optimize",
    "Compiler",
    "CompilationResult",
    # Resources
    "ResourceEstimator",
    "ResourceEstimate",
    # Backends
    "Backend",
    "BackendResult",
    "BackendCapabilities",
    "BackendAdapter",
    "BackendRegistry",
    "LocalSimulatorBackend",
    "MockBackend",
    "Provider",
    "LocalProvider",
    "TargetClass",
    "Job",
    "JobStatus",
    "StatevectorBackend",
    "DensityMatrixBackend",
    "MatrixProductState",
    "MPSBackend",
    "TreeTensorNetwork",
    "TreeTensorNetworkBackend",
    "NoiseModel",
    "NoiseChannel",
    "Executor",
    "ExecutorResult",
    "set_array_backend",
    "get_array_backend",
    "available_backends",
    "gpu_available",
    "is_gpu",
    # Optimizers
    "Optimizer",
    "OptimizerResult",
    "GradientDescent",
    "Adam",
    "BFGS",
    "COBYLA",
    "NelderMead",
    "SPSA",
    "QNSPSA",
    # Problems
    "Problem",
    "SamplingProblem",
    "OptimizationProblem",
    "HamiltonianProblem",
    "EigenvalueProblem",
    "SearchProblem",
    # Algorithms
    "Algorithm",
    "AlgorithmResult",
    "VQE",
    "VQEResult",
    "QAOA",
    "GroverSearch",
    "GroverResult",
    "AmplitudeEstimation",
    "AmplitudeEstimationResult",
    "QFT",
    "qft_circuit",
    "inverse_qft_circuit",
    "PhaseEstimation",
    "PhaseEstimationResult",
    "HamiltonianSimulation",
    "TrotterResult",
    "HHL",
    "HHLResult",
    "VQD",
    "VQDResult",
    "AdaptVQE",
    "AdaptResult",
    "DiscreteQuantumWalk",
    "ContinuousQuantumWalk",
    "QuantumWalkResult",
    "ShorsAlgorithm",
    "ShorResult",
    "BernsteinVazirani",
    "BVResult",
    "DeutschJozsa",
    "DJResult",
    "fourth_order_simulation",
    "qdrift_simulation",
    # QEC
    "RepetitionCode",
    "BitFlipCode",
    "PhaseFlipCode",
    "ShorCode",
    # Adapters
    "DomainAdapter",
    "QuantumProblem",
    "QuantumResult",
    "ResultCache",
    # QML
    "AngleEncoding",
    "AmplitudeEncoding",
    "IQPEncoding",
    "ZFeatureMap",
    "QuantumKernel",
    "VariationalClassifier",
    "ClassifierResult",
    # Mitigation
    "ZeroNoiseExtrapolation",
    "ExtrapolationResult",
    "ProbabilisticErrorCancellation",
    "MeasurementErrorMitigation",
    "MitigationMatrix",
    # Chemistry
    "MolecularHamiltonian",
    "H2Hamiltonian",
    "LiHHamiltonian",
    "HardwareEfficientAnsatz",
    "UCCSDAnsatz",
    # Benchmarks
    "QuantumVolumeBenchmark",
    "BenchmarkResult",
    "CLOPSBenchmark",
    "RandomizedBenchmarking",
    "RandomizedBenchmarkingResult",
    "CrossEntropyBenchmarking",
    "XEBResult",
    "GateSetTomography",
    "GSTResult",
    "CycleBenchmarking",
    "CycleBenchmarkingResult",
    "LayerFidelity",
    "LayerFidelityResult",
    "PauliTwirling",
    "TwirlingResult",
    # Analytics
    "AnalysisResult",
    "BaseAnalytics",
    "Result",
    # Analysis (MQ-07)
    "SamplingAnalysis",
    "ExpectationAnalysis",
    "StateAnalysis",
    "ResultAggregator",
    "mean",
    "variance",
    "standard_deviation",
    "standard_error",
    "confidence_interval",
    "minimum",
    "maximum",
    "count",
    # Experiments (MQ-07)
    "ExecutionRecord",
    "ExecutionFailure",
    "ExecutionStatus",
    "ParameterSweep",
    "Experiment",
    "ExperimentResult",
    "execution_fingerprint",
    "reproducibility_metadata",
    # Optimization
    "QUBOBuilder",
    "QUBOProblem",
    "IsingConverter",
    # Providers
    "HardwareProvider",
    "HardwareJob",
    "HardwareStatus",
    "ProviderCredentials",
    "HardwareBackend",
    "IBMQuantumCredentials",
    "IBMQuantumProvider",
    "IonQCredentials",
    "IonQProvider",
    "CircuitSerializer",
    "UnsupportedGateError",
    # Execution runtime
    "ExecutionPlan",
    "ExecutionRuntime",
    "RuntimeConfig",
    "runtime_info",
    "ExecutionStrategy",
    "ExecutionTrace",
    "TraceEvent",
    "STRATEGY_HANDLERS",
    "register_custom_strategy",
    "default_runtime",
    "execute",
    "submit",
    "execute_batch",
    "submit_batch",
    "execute_records",
    "run_experiment",
    "run_parameter_sweep",
    "run_hybrid",
]
